services:
  redis:
    image: redis:alpine
    container_name: redis_api_email
    restart: always
    env_file:
      - .env
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"